---
title: "第３・４回目"
author: "22MM337：星澤知宙"
date: "4/19/2021"
output:
  github_document
#  html_document:
#    toc: yes
#    toc_float: yes
    
---


## R Markdown

# chapter 2
```{r chapter2-1}
# this is comment
2+1
log(3)
exp(2.7)
```

```{r chapter2-2}
# object
my_obj = 48
My_obj = 48

# character
my_obj2 = "R study"
print(my_obj2)


#add
 my_obj + My_obj  # OK
#my_obj + my_obj2 # NG

 my_obj3 = "is cool."
#my_obj2 + my_obj3 #NG

paste(my_obj2, my_obj3)
```

```{r chapter2-3}
# vector
my_vec = c(3,5,2,46,6,10)
print(my_vec)
mean(my_vec)
var(my_vec)
sd(my_vec)
length(my_vec)

my_vec2 = c(3,5,2,46,6,10,NA)
var(my_vec2, na.rm=T)

my_seq = 1:10
print(my_seq)
my_seq2 = seq(from=1,to=5,by=0.5)
```

```{r chapter2-4}
print(my_vec)
print(my_vec[3]) # Rのインデックスは1から
val_3 = my_vec[3]

my_vec[c(1,5,6,8)]
id = c(1,5,6,8)
print(my_vec[id])

print(my_vec > 4)
my_vec[my_vec > 4]

id3 = my_vec < 6 & my_vec > 2
my_vec[id3]

id4 = my_vec > 6 | my_vec < 3
my_vec[id4]
```

# chapter 3
```{r chapter3-1}
num = 2.2
char = "hello."
logi = T
class(num)
class(char)
class(logi)

is.numeric(num)
is.character(char)
is.logical(logi)

num_char = as.character(num)
print(num_char)
class(num_char)
```

```{r chapter3-2}
my_mat = matrix(data=1:16, nrow=4, byrow=T)
print(my_mat)

my_array = array(data=1:16, dim=c(2,4,2))
print(my_array)
print(my_array[,,1]) # pythonから:を抜いた感じ
print(my_array[1,,])

rownames(my_mat) = c("A","B","C","D")
colnames(my_mat) = c("a","b","c","d")
my_mat

#list
list_1 = list(c("black", "yellow", "orange"),
             c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
             matrix(1:6, nrow = 3)) 
list_1

list_2 = list(colors = c("black", "yellow", "orange"),
              evaluation = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
              time = matrix(1:6, nrow = 3))
list_2
list_2$colors
str(list_2) #structures

#data frames
#pandasに近い
p.height <- c(180, 155, 160, 167, 181)
p.weight <- c(65, 50, 52, 58, 70)
p.names <- c("Joanna", "Charlotte", "Helen", "Karen", "Amy")

dataf = data.frame(height=p.height, weight=p.weight, names=p.names)
dataf
dim(dataf)
str(dataf)
dataf$height
```

```{r chapter3-3}
flower <- read.csv("~/class/l03-04/flower.csv")
str(flower)
```

```{r chapter3-4}
flower$height
summary(flower$height)

#3.4.1
flower[1,4] # 1行4列目の要素
flower[,c(1,4)] # 1列目と4列目
flower[c(1,4),] # 1行目と4行目
```

# tidyverse
```{r tidyverse} 
#モダンなR言語のパッケージ
library(tidyverse)
flower %>% select(height)
flower %>% select(height, weight)
flower %>% select(-height, -weight)
flower_height = flower %>% select(height)
flower_height
head(flower)

flower %>% filter(nitrogen == "high")
flower %>%
  filter(nitrogen == "high") %>%
  filter(height > 13) %>%
  select(height, weight)

#data frameでどう処理するか(問題)
flower[flower$nitrogen=="high" & flower$height>13, c("height","weight")]

id1 = flower$nitrogen=="high"
id2 = flower$height>13
id3 = id1 & id2
flower[id3, c("height","weight")]

#add column
flower2 = flower %>%
  mutate(height_cm = height/10)
flower2
```

# chapter 6
```{r chapter6-3}
#y ~ x1 + x2
#weight = height ~ leafarea

flower

# linear modelling
ans = lm(weight ~ height + leafarea, data=flower)
summary(ans)
plot(ans)
```

# chapter 7
```{r chapter7}
test_func = function(x){
  y = x-1
  return(y)
}

test_func(4)

for(i in 1:5){
  print(i)
}
```
